name: Build KumbhStay 3 APKs

on:
  workflow_dispatch:

jobs:

  company:
    name: Company App
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses >/dev/null || true

      - name: Build Company APK
        working-directory: KumbhStay-Company
        run: gradle assembleDebug

      - name: Save Company APK
        uses: actions/upload-artifact@v4
        with:
          name: KumbhStay-Company-APK
          path: KumbhStay-Company/app/build/outputs/apk/debug/app-debug.apk


  customer:
    name: Customer App
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses >/dev/null || true

      - name: Build Customer APK
        working-directory: KumbhStay-Customer
        run: gradle assembleDebug

      - name: Save Customer APK
        uses: actions/upload-artifact@v4
        with:
          name: KumbhStay-Customer-APK
          path: KumbhStay-Customer/app/build/outputs/apk/debug/app-debug.apk


  hotelowner:
    name: Hotel Owner App
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses >/dev/null || true

      - name: Build Hotel Owner APK
        working-directory: KumbhStay-HotelOwner
        run: gradle assembleDebug

      - name: Save Hotel Owner APK
        uses: actions/upload-artifact@v4
        with:
          name: KumbhStay-HotelOwner-APK
          path: KumbhStay-HotelOwner/app/build/outputs/apk/debug/app-debug.apk
